version: '3'
services:
  db:
    image: postgres
    volumes:
      - /root/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stockerize_prod
